'use client';
import {useEffect,useMemo,useState} from 'react';
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid,AreaChart,Area} from 'recharts';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type Snapshot={symbol:string,price:number,change:number,trend:string,score:number,rsi:number,vwap:number,ema20:number,ema50:number,support:number,resistance:number,atr:number};
type ChainRow={strike:number,call_ltp:number,call_oi:number,call_chg_oi:number,put_ltp:number,put_oi:number,put_chg_oi:number};
export default function Home(){
 const [snap,setSnap]=useState<Snapshot[]>([]); const [chain,setChain]=useState<ChainRow[]>([]); const [symbol,setSymbol]=useState('NIFTY'); const [mode,setMode]=useState('PAPER'); const [risk,setRisk]=useState(1); const [capital,setCapital]=useState(100000); const [status,setStatus]=useState('Loading…');
 const [chart,setChart]=useState<any[]>([]);
 async function load(){try{const s=await fetch(`${API}/api/v1/market/snapshot`).then(r=>r.json());setSnap(s.items); const c=await fetch(`${API}/api/v1/options/chain?symbol=${symbol}`).then(r=>r.json());setChain(c.rows); const h=await fetch(`${API}/api/v1/market/history?symbol=${symbol}`).then(r=>r.json());setChart(h.candles);setStatus('Connected to ALICE API')}catch(e){setStatus('Demo/offline mode')}}
 useEffect(()=>{load();const id=setInterval(load,15000);return()=>clearInterval(id)},[symbol]);
 const active=useMemo(()=>snap.find(x=>x.symbol===symbol)||snap[0],[snap,symbol]);
 const setup=useMemo(()=>{if(!active)return null;const bullish=active.trend==='BULLISH';const direction=bullish?'CE':'PE';const entry=bullish?active.price*0.01:active.price*0.01;const sl=entry*0.78;const t1=entry*1.35;const t2=entry*1.65;const probability=Math.min(92,Math.max(52,active.score-4));return {direction,entry,sl,t1,t2,probability,rr:2.1}},[active]);
 return <main><header><div><div className="brand">ALICE</div><div className="sub">ULTIMATE F&O INTELLIGENCE</div></div><div className="headerRight"><span className="live">● LIVE API</span><select value={mode} onChange={e=>setMode(e.target.value)}><option>PAPER</option><option>ADVISORY</option><option>LIVE (LOCKED)</option></select></div></header>
 <section className="hero"><div><h1>Market Command Center</h1><p>Rules + risk controls + analytics. ALICE can choose <b>NO TRADE</b> when conditions are weak.</p></div><div className="status">{status}</div></section>
 <div className="ticker">{snap.map(x=><button className={symbol===x.symbol?'activeTicker':''} onClick={()=>setSymbol(x.symbol)} key={x.symbol}><span>{x.symbol}</span><b>{x.price.toFixed(2)}</b><em className={x.change>=0?'up':'down'}>{x.change>=0?'+':''}{x.change.toFixed(2)}%</em></button>)}</div>
 <section className="grid top"><article className="card chartCard"><div className="cardHead"><h2>{symbol} price action</h2><span>5m</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopOpacity={.25}/><stop offset="95%" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" opacity={.08}/><XAxis dataKey="time" hide/><YAxis domain={['auto','auto']} width={55}/><Tooltip/><Area type="monotone" dataKey="close" strokeWidth={2} fill="url(#g)"/><Line type="monotone" dataKey="ema20" strokeWidth={1.5} dot={false}/><Line type="monotone" dataKey="vwap" strokeWidth={1.5} dot={false}/></AreaChart></ResponsiveContainer></div></article>
 <article className="card"><div className="cardHead"><h2>ALICE market state</h2><span className="pill">{active?.trend||'—'}</span></div><div className="score"><div><strong>{active?.score??'—'}</strong><small>/100</small></div><div><b>{active?.trend||'WAIT'}</b><p>Trend confidence score</p></div></div><div className="metrics"><Metric n="RSI" v={active?.rsi.toFixed(1)}/><Metric n="VWAP" v={active?.vwap.toFixed(2)}/><Metric n="EMA 20" v={active?.ema20.toFixed(2)}/><Metric n="EMA 50" v={active?.ema50.toFixed(2)}/><Metric n="Support" v={active?.support.toFixed(2)}/><Metric n="Resistance" v={active?.resistance.toFixed(2)}/></div></article></section>
 <section className="grid mid"><article className="card"><div className="cardHead"><h2>ALICE setup engine</h2><span className="pill">{setup?.direction||'NO TRADE'}</span></div>{setup?<><div className="setupGrid"><Metric n="Direction" v={setup.direction}/><Metric n="Entry" v={`₹${setup.entry.toFixed(2)}`}/><Metric n="Stop loss" v={`₹${setup.sl.toFixed(2)}`}/><Metric n="Target 1" v={`₹${setup.t1.toFixed(2)}`}/><Metric n="Target 2" v={`₹${setup.t2.toFixed(2)}`}/><Metric n="R:R" v={`1:${setup.rr}`}/></div><div className="confidence"><div><span>AI probability</span><b>{setup.probability}%</b></div><div className="bar"><i style={{width:`${setup.probability}%`}}/></div></div><button className="primary">PAPER TRADE {setup.direction}</button></>:<p>Waiting for market data.</p>}</article>
 <article className="card"><div className="cardHead"><h2>Risk engine</h2><span className="pill">GUARDED</span></div><label>Capital ₹<input type="number" value={capital} onChange={e=>setCapital(+e.target.value)}/></label><label>Risk / trade %<input type="number" min="0.1" max="2" step="0.1" value={risk} onChange={e=>setRisk(+e.target.value)}/></label><div className="riskBox"><span>Max loss / trade</span><b>₹{(capital*risk/100).toFixed(0)}</b></div><div className="riskBox"><span>Daily loss limit</span><b>₹{(capital*0.03).toFixed(0)}</b></div><p className="muted">Live execution remains locked until broker credentials, risk gates and explicit live mode are enabled.</p></article></section>
 <section className="card"><div className="cardHead"><h2>Option chain intelligence</h2><span>PCR / OI / strike map</span></div><div className="chainWrap"><table><thead><tr><th>Call OI</th><th>Call ΔOI</th><th>Call LTP</th><th>STRIKE</th><th>Put LTP</th><th>Put ΔOI</th><th>Put OI</th></tr></thead><tbody>{chain.map(r=><tr key={r.strike}><td>{r.call_oi.toLocaleString()}</td><td>{r.call_chg_oi.toLocaleString()}</td><td>{r.call_ltp.toFixed(2)}</td><th>{r.strike}</th><td>{r.put_ltp.toFixed(2)}</td><td>{r.put_chg_oi.toLocaleString()}</td><td>{r.put_oi.toLocaleString()}</td></tr>)}</tbody></table></div></section>
 <section className="stageGrid">{['01 Market','02 Options','03 Strategy','04 Risk','05 Paper','06 Backtest','07 Alerts','08 Broker','09 Automation'].map((s,i)=><div className={'stage '+(i<7?'ready':'locked')} key={s}><span>{s}</span><b>{i<7?'READY':'LOCKED'}</b></div>)}</section>
 <footer>ALICE Ultimate v1 · Decision support only · Demo data unless a verified provider is connected</footer></main>}
function Metric({n,v}:{n:string,v?:string}){return <div className="metric"><span>{n}</span><b>{v??'—'}</b></div>}
